export const resourceGroupApplications: Record<string, string> = {
  "rg-creditai-qa-001": "CreditAI - QA",
  "rg-creditai-lz-public-001": "CreditAI - Prod",
  "rg-ocm20_obe-dev-001": "OCM20 OBE",
  "rg-ocm20_evolve-dev-001": "OCM20 Evolve (EA Sandbox)",
  "rg-ocmevl-lz-public-001": "OCM20 Evolve (Landing Zone)",
  "rg-devaiocm1": "Knowledge Assistant V1.0 Shared Resources",
  "rg-ka-shared_resources-001": "Knowledge Assistant V2.0 Shared Resources",
  "rg-ocmka20-dev": "OCM KA (Microsoft team's resources)",
  "rg-alta-qa-01": "ALTA - QA",
  "rg-contractinv-qa-001": "AI Invoice",
  "rg-devai-contentgen": "Content Generation",
  "rg-actpto-lz-prod-001": "PTO - Prod",
  "rg-resume-ranker-dev-001": "Resume Ranker",
};

export const resourceApplications: Record<string, string> = {
  prodaiwebfxapp: "ALTA - Prod",
  "asp-devaiteam-83e2": "ALTA - Prod",
  prodaidb: "ALTA - Prod",
  prodaitranslationstorage: "ALTA - Prod",
  prodaitranslatorus2: "ALTA - Prod",
  "dev-app": "ALTA - Prod",
  prodwebfxapp: "ALTA - Prod",
  "ag-alta-prod-001": "ALTA - Prod",
  "alert-alta-prod-http5xx": "ALTA - Prod",
  "alert-alta-prod-healthcheck": "ALTA - Prod",
  devaiwebfunctions: "ALTA - QA",
  "asp-alta-qa-001": "ALTA - QA",
  "settings-details": "Shared QA Database",
  devaitranslationstorage: "ALTA - QA",
  "devai-translation": "ALTA - QA",
  "apin-alta-qa-001": "ALTA - QA",
  "7b2f5ca9-5d55-4ff0-abc9-fea4aac92490-rg-alta-qa-01-EUS2": "ALTA - QA",
  "test-pipe": "ALTA - QA",
  "cosmos-alta-qa-001": "ALTA - QA",
  "pto-qa-backend-webapp": "PTO - QA",
  "asp-devaiteam-8c71": "PTO - QA",
  "pto-static-webapp": "PTO - QA",
  prodFinal: "PTO - QA",
  "ag-pto-qa-alerts": "PTO - QA",
  "alert-pto-qa-healthcheck": "PTO - QA",
  "pto-qa-http5xx": "PTO - QA",
  "aif-pto-qa": "PTO - QA",
  "7b2f5ca9-5d55-4ff0-abc9-fea4aac92490-devaiteam-eus2":
    "PTO - QA, ALTA - Prod (Shared)",
  "qa-azure-search": "OBE 1.0",
  "asp-rgdevaiocm1-bc22": "OBE 1.0",
  "logic-filesync-addupdate-bullhorn": "OBE 1.0",
  "logic-filesync-addupdate-interimpilotjob": "OBE 1.0",
  "logic-filesync-addupdate-CRG": "OBE 1.0",
  "logic-filesync-addupdate-OBE": "OBE 1.0",
  "logic-filesync-delete-OBE": "OBE 1.0",
  "logic-filesync-delete-interimpilotjob": "OBE 1.0",
  "logic-filesync-delete-bullhorn": "OBE 1.0",
  "logic-filesync-delete-CRG": "OBE 1.0",
  "azuresearch-qa-ui": "OBE 1.0",
  "app-azuresearch-qa-evolve": "Evolve 1.0",
  "asp-evolve-instance": "Evolve 1.0",
  "logic-filesync-qa": "Evolve 1.0",
  "logic-filesync-addupdate-evolve-globalservices": "Evolve 1.0",
  "logic-filesync-addupdate-evolve-fieldsupportgroup": "Evolve 1.0",
  "logic-filesync-addupdate-evolve-evolveEBO": "Evolve 1.0",
  "logic-filesync-addupdate-evolve-OSGFSG": "Evolve 1.0",
  "logic-filesync-delete-evolve-globalservices": "Evolve 1.0",
  "logic-filesync-delete-evolve-fieldsupportgroup": "Evolve 1.0",
  "logic-filesync-delete-evolve-OSGFSG": "Evolve 1.0",
  "logic-filesync-delete-evolve-evolveEBO": "Evolve 1.0",
  "swa-azuresearch-qa-evolve": "Evolve 1.0",
  "app-azuresearch-qa-ps-esa": "PeopleSoft ESA",
  "asp-azuresearch-qa-ps-esa": "PeopleSoft ESA",
  "swa-azuresearch-qa-ps-esa": "PeopleSoft ESA",
  "app-azuresearch-qa-emo": "Evolve Middle Office",
  "swa-azuresearch-qa-emo": "Evolve Middle Office",
  "pto-prod-backend-webapp": "PTO - Prod (Sandbox Subscription)",
  "webapp-plan-prod": "PTO - Prod (Sandbox Subscription)",
  "pto-prod-qa-staticwebapp": "PTO - Prod (Sandbox Subscription)",
  "search-ocmka20-dev": "Knowledge Assistant V2.0 Shared Resources",
};

export const applicationOwnership: Record<string, { project: string; environment: string }> = {
  "ALTA - Prod": { project: "ALTA", environment: "Production" },
  "ALTA - QA": { project: "ALTA", environment: "QA" },
  "PTO - QA": { project: "PTO", environment: "QA" },
  "PTO - Prod": { project: "PTO", environment: "Production" },
  "PTO - Prod (Sandbox Subscription)": { project: "PTO", environment: "Decommissioned" },
  "CreditAI - QA": { project: "CreditAI", environment: "QA" },
  "CreditAI - Prod": { project: "CreditAI", environment: "Production" },
  "OCM20 OBE": { project: "Knowledge Assistant", environment: "Production" },
  "OBE 1.0": { project: "Knowledge Assistant", environment: "Decommissioned" },
  "OCM20 Evolve (EA Sandbox)": { project: "Knowledge Assistant", environment: "Production" },
  "OCM20 Evolve (Landing Zone)": {
    project: "Knowledge Assistant",
    environment: "Pre-Production (Future Prod)",
  },
  "Evolve 1.0": { project: "Knowledge Assistant", environment: "Decommissioned" },
  "Evolve Middle Office": { project: "Knowledge Assistant", environment: "QA" },
  "PeopleSoft ESA": { project: "Knowledge Assistant", environment: "QA" },
  "Knowledge Assistant V1.0 Shared Resources": {
    project: "Knowledge Assistant",
    environment: "QA",
  },
  "Knowledge Assistant V2.0 Shared Resources": {
    project: "Knowledge Assistant",
    environment: "Production",
  },
  "AI Invoice": { project: "AI Invoice", environment: "QA" },
  "Content Generation": { project: "Content Generation", environment: "QA" },
  "Resume Ranker": { project: "Resume Ranker", environment: "QA" },
  "OCM KA (Microsoft team's resources)": {
    project: "Knowledge Assistant",
    environment: "Dev / POC",
  },
  "Shared QA Database": { project: "Miscellaneous", environment: "QA" },
  "PTO - QA, ALTA - Prod (Shared)": {
    project: "Miscellaneous",
    environment: "Shared (Prod/QA)",
  },
  Unmapped: { project: "Miscellaneous", environment: "Dev / POC" },
};

export const resourceTypeBillingModels: Record<string, string> = {
  "App Service plan": "Fixed",
  "microsoft.dbforpostgresql/servergroupsv2": "Fixed",
  Translator: "Usage-Based",
  "Static Web App": "Fixed",
  "microsoft.insights/scheduledqueryrules": "Usage-Based",
  "Storage account": "Usage-Based",
  "microsoft.insights/metricalerts": "Usage-Based",
  "App Service web app": "N/A",
  "microsoft.insights/actiongroups": "N/A",
  "Log Analytics workspace": "Usage-Based",
  "Document Intelligence": "Usage-Based",
  "Logic app": "Usage-Based",
  "Private endpoint": "Hybrid",
  "Private DNS zone": "Hybrid",
  "Cosmos DB account": "Usage-Based",
  "Search service": "Fixed",
  "Azure AI services multi-service account": "Usage-Based",
  "Key vault": "Usage-Based",
  SaaS: "N/A",
  "microsoft.cdn/profiles": "Usage-Based",
  "Container registry": "Hybrid",
  "microsoft.machinelearningservices/workspaces": "Usage-Based",
  "Cognitive Services account": "Usage-Based",
  "Azure Document Intelligence": "Usage-Based",
  "Azure Translator": "Usage-Based",
};
